### ISSUE TITLE
Include `publishedAt` in getArticles() response

### ISSUE THREAD

**Issue by edhollinghurst** [MarsX-dev/seobot#1]
Is there any reason why this isn't included?

It's available when fetching an article individually using `getArticle()`.

**Comment by vitalikmay** [comment]
Added 'updatedAt' property that can be used as 'publishedAt' https://github.com/MarsX-dev/seobot/commit/a1bbab760cbcf5412cdbed1d3b5e09f5a02cb2cb

@edhollinghurst you have to do Menu -> Blog Sync Status -> Reset Cache in the SEObot app
